version: "3.8"

name: "selt-team-project"

services: 
  app:
    container_name: team_app
    build: ./
    command: bundle exec puma -C config/puma.rb
    working_dir: /app
    volumes: 
      - .:/app
    ports: 
      - "3000:3000"
    env_file:
      - .env.prod
    depends_on:
      - pg
  pg: 
    image: postgres:13.1-alpine
    container_name: prod_db
    volumes: 
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.prod
    ports:
      - "5432:5432"
    