version: "3.8"
networks: 
  default:
    name: selt-team-project
services: 
  app:
    container_name: team_app
    build: ./
    command: bundle exec puma -C config/puma.rb
    working_dir: /app
    volumes: 
      - .:/app
    ports: 
      - "3000:3000"
    env_file:
      - .env