version: "3.8"

name: integration

services: 
  app:
    container_name: int2
    build: ./
    command: bundle exec puma -C config/puma.rb
    working_dir: /app
    volumes: 
      - .:/app
    ports: 
      - "3000:3000"
    env_file:
      - .env