version: "3.8"

name: "selt-team-project"

services: 
  app:
    platform: linux/x86_64 
    container_name: team_app
    build: ./
    command: bundle exec puma -C config/puma.rb
    working_dir: /app
    volumes: 
      - .:/app
    ports: 
      - "3000:3000"
  #   depends_on:
  #     - prod_db
  # prod_db: 
  #   container_name: pg
  #   image: postgres:13.1-alpine
  #   env_file:
  #     - .env
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data
